// <auto-generated />
using System;
using EmptyProjectTesting.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmptyProjectTesting.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmptyProjectTesting.Entites.CountryFlag", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CapitalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("CountryFlag", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "AF",
                            CapitalName = "Kabul",
                            CountryName = "Afghanistan",
                            CurrencyName = "Afghani"
                        },
                        new
                        {
                            Code = "AL",
                            CapitalName = "Tirana",
                            CountryName = "Albania",
                            CurrencyName = "Lek"
                        },
                        new
                        {
                            Code = "DZ",
                            CapitalName = "Algiers",
                            CountryName = "Algeria",
                            CurrencyName = "Algerian Dinar"
                        },
                        new
                        {
                            Code = "AD",
                            CapitalName = "Andorra la Vella",
                            CountryName = "Andorra",
                            CurrencyName = "Euro"
                        },
                        new
                        {
                            Code = "AO",
                            CapitalName = "Luanda",
                            CountryName = "Angola",
                            CurrencyName = "Kwanza"
                        },
                        new
                        {
                            Code = "AG",
                            CapitalName = "Saint John's",
                            CountryName = "Antigua and Barbuda",
                            CurrencyName = "East Caribbean Dollar"
                        },
                        new
                        {
                            Code = "AR",
                            CapitalName = "Buenos Aires",
                            CountryName = "Argentina",
                            CurrencyName = "Argentine Peso"
                        },
                        new
                        {
                            Code = "AM",
                            CapitalName = "Yerevan",
                            CountryName = "Armenia",
                            CurrencyName = "Armenian Dram"
                        },
                        new
                        {
                            Code = "AU",
                            CapitalName = "Canberra",
                            CountryName = "Australia",
                            CurrencyName = "Australian Dollar"
                        },
                        new
                        {
                            Code = "AT",
                            CapitalName = "Vienna",
                            CountryName = "Austria",
                            CurrencyName = "Euro"
                        },
                        new
                        {
                            Code = "AZ",
                            CapitalName = "Baku",
                            CountryName = "Azerbaijan",
                            CurrencyName = "Azerbaijani Manat"
                        },
                        new
                        {
                            Code = "BS",
                            CapitalName = "Nassau",
                            CountryName = "Bahamas",
                            CurrencyName = "Bahamian Dollar"
                        },
                        new
                        {
                            Code = "BH",
                            CapitalName = "Manama",
                            CountryName = "Bahrain",
                            CurrencyName = "Bahraini Dinar"
                        },
                        new
                        {
                            Code = "BD",
                            CapitalName = "Dhaka",
                            CountryName = "Bangladesh",
                            CurrencyName = "Taka"
                        },
                        new
                        {
                            Code = "BB",
                            CapitalName = "Bridgetown",
                            CountryName = "Barbados",
                            CurrencyName = "Barbadian Dollar"
                        },
                        new
                        {
                            Code = "BY",
                            CapitalName = "Minsk",
                            CountryName = "Belarus",
                            CurrencyName = "Belarusian Ruble"
                        },
                        new
                        {
                            Code = "BE",
                            CapitalName = "Brussels",
                            CountryName = "Belgium",
                            CurrencyName = "Euro"
                        },
                        new
                        {
                            Code = "BZ",
                            CapitalName = "Belmopan",
                            CountryName = "Belize",
                            CurrencyName = "Belize Dollar"
                        },
                        new
                        {
                            Code = "BJ",
                            CapitalName = "Porto-Novo",
                            CountryName = "Benin",
                            CurrencyName = "West African CFA Franc"
                        },
                        new
                        {
                            Code = "BT",
                            CapitalName = "Thimphu",
                            CountryName = "Bhutan",
                            CurrencyName = "Ngultrum"
                        },
                        new
                        {
                            Code = "BO",
                            CapitalName = "Sucre",
                            CountryName = "Bolivia",
                            CurrencyName = "Boliviano"
                        },
                        new
                        {
                            Code = "BA",
                            CapitalName = "Sarajevo",
                            CountryName = "Bosnia and Herzegovina",
                            CurrencyName = "Convertible Mark"
                        },
                        new
                        {
                            Code = "BW",
                            CapitalName = "Gaborone",
                            CountryName = "Botswana",
                            CurrencyName = "Pula"
                        },
                        new
                        {
                            Code = "BR",
                            CapitalName = "Brasilia",
                            CountryName = "Brazil",
                            CurrencyName = "Brazilian Real"
                        },
                        new
                        {
                            Code = "BN",
                            CapitalName = "Bandar Seri Begawan",
                            CountryName = "Brunei",
                            CurrencyName = "Brunei Dollar"
                        },
                        new
                        {
                            Code = "BG",
                            CapitalName = "Sofia",
                            CountryName = "Bulgaria",
                            CurrencyName = "Bulgarian Lev"
                        },
                        new
                        {
                            Code = "BF",
                            CapitalName = "Ouagadougou",
                            CountryName = "Burkina Faso",
                            CurrencyName = "West African CFA Franc"
                        },
                        new
                        {
                            Code = "BI",
                            CapitalName = "Gitega",
                            CountryName = "Burundi",
                            CurrencyName = "Burundian Franc"
                        },
                        new
                        {
                            Code = "CV",
                            CapitalName = "Praia",
                            CountryName = "Cabo Verde",
                            CurrencyName = "Cape Verdean Escudo"
                        },
                        new
                        {
                            Code = "KH",
                            CapitalName = "Phnom Penh",
                            CountryName = "Cambodia",
                            CurrencyName = "Riel"
                        },
                        new
                        {
                            Code = "CM",
                            CapitalName = "Yaounde",
                            CountryName = "Cameroon",
                            CurrencyName = "Central African CFA Franc"
                        },
                        new
                        {
                            Code = "CA",
                            CapitalName = "Ottawa",
                            CountryName = "Canada",
                            CurrencyName = "Canadian Dollar"
                        },
                        new
                        {
                            Code = "CF",
                            CapitalName = "Bangui",
                            CountryName = "Central African Republic",
                            CurrencyName = "Central African CFA    Franc"
                        },
                        new
                        {
                            Code = "TD",
                            CapitalName = "N'Djamena",
                            CountryName = "Chad",
                            CurrencyName = "Central African CFA Franc"
                        },
                        new
                        {
                            Code = "CL",
                            CapitalName = "Santiago",
                            CountryName = "Chile",
                            CurrencyName = "Chilean Peso"
                        },
                        new
                        {
                            Code = "CN",
                            CapitalName = "Beijing",
                            CountryName = "China",
                            CurrencyName = "Chinese Yuan"
                        },
                        new
                        {
                            Code = "CO",
                            CapitalName = "Bogota",
                            CountryName = "Colombia",
                            CurrencyName = "Colombian Peso"
                        },
                        new
                        {
                            Code = "KM",
                            CapitalName = "Moroni",
                            CountryName = "Comoros",
                            CurrencyName = "Comorian Franc"
                        },
                        new
                        {
                            Code = "CG",
                            CapitalName = "Brazzaville",
                            CountryName = "Republic of the Congo",
                            CurrencyName = "Central African CFA  Franc"
                        },
                        new
                        {
                            Code = "CD",
                            CapitalName = "Kinshasa",
                            CountryName = "Democratic Republic of the Congo",
                            CurrencyName = "Congolese    Franc"
                        },
                        new
                        {
                            Code = "CR",
                            CapitalName = "San Jose",
                            CountryName = "Costa Rica",
                            CurrencyName = "Costa Rican Colon"
                        },
                        new
                        {
                            Code = "CI",
                            CapitalName = "Yamoussoukro",
                            CountryName = "Cote d'Ivoire",
                            CurrencyName = "West African CFA Franc"
                        },
                        new
                        {
                            Code = "HR",
                            CapitalName = "Zagreb",
                            CountryName = "Croatia",
                            CurrencyName = "Euro"
                        },
                        new
                        {
                            Code = "CU",
                            CapitalName = "Havana",
                            CountryName = "Cuba",
                            CurrencyName = "Cuban Peso"
                        },
                        new
                        {
                            Code = "CY",
                            CapitalName = "Nicosia",
                            CountryName = "Cyprus",
                            CurrencyName = "Euro"
                        },
                        new
                        {
                            Code = "CZ",
                            CapitalName = "Prague",
                            CountryName = "Czech Republic",
                            CurrencyName = "Czech Koruna"
                        },
                        new
                        {
                            Code = "DK",
                            CapitalName = "Copenhagen",
                            CountryName = "Denmark",
                            CurrencyName = "Danish Krone"
                        },
                        new
                        {
                            Code = "DJ",
                            CapitalName = "Djibouti",
                            CountryName = "Djibouti",
                            CurrencyName = "Djiboutian Franc"
                        },
                        new
                        {
                            Code = "DM",
                            CapitalName = "Roseau",
                            CountryName = "Dominica",
                            CurrencyName = "East Caribbean Dollar"
                        },
                        new
                        {
                            Code = "DO",
                            CapitalName = "Santo Domingo",
                            CountryName = "Dominican Republic",
                            CurrencyName = "Dominican Peso"
                        },
                        new
                        {
                            Code = "EC",
                            CapitalName = "Quito",
                            CountryName = "Ecuador",
                            CurrencyName = "US Dollar"
                        },
                        new
                        {
                            Code = "EG",
                            CapitalName = "Cairo",
                            CountryName = "Egypt",
                            CurrencyName = "Egyptian Pound"
                        },
                        new
                        {
                            Code = "SV",
                            CapitalName = "San Salvador",
                            CountryName = "El Salvador",
                            CurrencyName = "US Dollar"
                        },
                        new
                        {
                            Code = "GQ",
                            CapitalName = "Malabo",
                            CountryName = "Equatorial Guinea",
                            CurrencyName = "Central African CFA Franc"
                        },
                        new
                        {
                            Code = "ER",
                            CapitalName = "Asmara",
                            CountryName = "Eritrea",
                            CurrencyName = "Nakfa"
                        },
                        new
                        {
                            Code = "EE",
                            CapitalName = "Tallinn",
                            CountryName = "Estonia",
                            CurrencyName = "Euro"
                        },
                        new
                        {
                            Code = "SZ",
                            CapitalName = "Mbabane",
                            CountryName = "Eswatini",
                            CurrencyName = "Lilangeni"
                        },
                        new
                        {
                            Code = "ET",
                            CapitalName = "Addis Ababa",
                            CountryName = "Ethiopia",
                            CurrencyName = "Birr"
                        },
                        new
                        {
                            Code = "FJ",
                            CapitalName = "Suva",
                            CountryName = "Fiji",
                            CurrencyName = "Fijian Dollar"
                        },
                        new
                        {
                            Code = "FI",
                            CapitalName = "Helsinki",
                            CountryName = "Finland",
                            CurrencyName = "Euro"
                        },
                        new
                        {
                            Code = "FR",
                            CapitalName = "Paris",
                            CountryName = "France",
                            CurrencyName = "Euro"
                        },
                        new
                        {
                            Code = "GA",
                            CapitalName = "Libreville",
                            CountryName = "Gabon",
                            CurrencyName = "Central African CFA Franc"
                        },
                        new
                        {
                            Code = "GM",
                            CapitalName = "Banjul",
                            CountryName = "Gambia",
                            CurrencyName = "Dalasi"
                        },
                        new
                        {
                            Code = "GE",
                            CapitalName = "Tbilisi",
                            CountryName = "Georgia",
                            CurrencyName = "Georgian Lari"
                        },
                        new
                        {
                            Code = "DE",
                            CapitalName = "Berlin",
                            CountryName = "Germany",
                            CurrencyName = "Euro"
                        },
                        new
                        {
                            Code = "GH",
                            CapitalName = "Accra",
                            CountryName = "Ghana",
                            CurrencyName = "Ghanaian Cedi"
                        },
                        new
                        {
                            Code = "GR",
                            CapitalName = "Athens",
                            CountryName = "Greece",
                            CurrencyName = "Euro"
                        },
                        new
                        {
                            Code = "GD",
                            CapitalName = "St. George's",
                            CountryName = "Grenada",
                            CurrencyName = "East Caribbean Dollar"
                        },
                        new
                        {
                            Code = "GT",
                            CapitalName = "Guatemala City",
                            CountryName = "Guatemala",
                            CurrencyName = "Quetzal"
                        },
                        new
                        {
                            Code = "GN",
                            CapitalName = "Conakry",
                            CountryName = "Guinea",
                            CurrencyName = "Guinean Franc"
                        },
                        new
                        {
                            Code = "GW",
                            CapitalName = "Bissau",
                            CountryName = "Guinea-Bissau",
                            CurrencyName = "West African CFA Franc"
                        },
                        new
                        {
                            Code = "GY",
                            CapitalName = "Georgetown",
                            CountryName = "Guyana",
                            CurrencyName = "Guyanese Dollar"
                        },
                        new
                        {
                            Code = "HT",
                            CapitalName = "Port-au-Prince",
                            CountryName = "Haiti",
                            CurrencyName = "Gourde"
                        },
                        new
                        {
                            Code = "HN",
                            CapitalName = "Tegucigalpa",
                            CountryName = "Honduras",
                            CurrencyName = "Lempira"
                        },
                        new
                        {
                            Code = "HU",
                            CapitalName = "Budapest",
                            CountryName = "Hungary",
                            CurrencyName = "Forint"
                        },
                        new
                        {
                            Code = "IS",
                            CapitalName = "Reykjavik",
                            CountryName = "Iceland",
                            CurrencyName = "Icelandic Krona"
                        },
                        new
                        {
                            Code = "IN",
                            CapitalName = "New Delhi",
                            CountryName = "India",
                            CurrencyName = "Indian Rupee"
                        },
                        new
                        {
                            Code = "ID",
                            CapitalName = "Jakarta",
                            CountryName = "Indonesia",
                            CurrencyName = "Rupiah"
                        },
                        new
                        {
                            Code = "IR",
                            CapitalName = "Tehran",
                            CountryName = "Iran",
                            CurrencyName = "Iranian Rial"
                        },
                        new
                        {
                            Code = "IQ",
                            CapitalName = "Baghdad",
                            CountryName = "Iraq",
                            CurrencyName = "Iraqi Dinar"
                        },
                        new
                        {
                            Code = "IE",
                            CapitalName = "Dublin",
                            CountryName = "Ireland",
                            CurrencyName = "Euro"
                        },
                        new
                        {
                            Code = "IL",
                            CapitalName = "Jerusalem",
                            CountryName = "Israel",
                            CurrencyName = "Israeli New Shekel"
                        },
                        new
                        {
                            Code = "IT",
                            CapitalName = "Rome",
                            CountryName = "Italy",
                            CurrencyName = "Euro"
                        },
                        new
                        {
                            Code = "JM",
                            CapitalName = "Kingston",
                            CountryName = "Jamaica",
                            CurrencyName = "Jamaican Dollar"
                        },
                        new
                        {
                            Code = "JP",
                            CapitalName = "Tokyo",
                            CountryName = "Japan",
                            CurrencyName = "Japanese Yen"
                        },
                        new
                        {
                            Code = "JO",
                            CapitalName = "Amman",
                            CountryName = "Jordan",
                            CurrencyName = "Jordanian Dinar"
                        },
                        new
                        {
                            Code = "KZ",
                            CapitalName = "Astana",
                            CountryName = "Kazakhstan",
                            CurrencyName = "Tenge"
                        },
                        new
                        {
                            Code = "KE",
                            CapitalName = "Nairobi",
                            CountryName = "Kenya",
                            CurrencyName = "Kenyan Shilling"
                        },
                        new
                        {
                            Code = "KI",
                            CapitalName = "South Tarawa",
                            CountryName = "Kiribati",
                            CurrencyName = "Australian Dollar"
                        },
                        new
                        {
                            Code = "KP",
                            CapitalName = "Pyongyang",
                            CountryName = "North Korea",
                            CurrencyName = "North Korean Won"
                        },
                        new
                        {
                            Code = "KR",
                            CapitalName = "Seoul",
                            CountryName = "South Korea",
                            CurrencyName = "South Korean Won"
                        },
                        new
                        {
                            Code = "KW",
                            CapitalName = "Kuwait City",
                            CountryName = "Kuwait",
                            CurrencyName = "Kuwaiti Dinar"
                        },
                        new
                        {
                            Code = "KG",
                            CapitalName = "Bishkek",
                            CountryName = "Kyrgyzstan",
                            CurrencyName = "Som"
                        },
                        new
                        {
                            Code = "LA",
                            CapitalName = "Vientiane",
                            CountryName = "Laos",
                            CurrencyName = "Kip"
                        },
                        new
                        {
                            Code = "LV",
                            CapitalName = "Riga",
                            CountryName = "Latvia",
                            CurrencyName = "Euro"
                        },
                        new
                        {
                            Code = "LB",
                            CapitalName = "Beirut",
                            CountryName = "Lebanon",
                            CurrencyName = "Lebanese Pound"
                        },
                        new
                        {
                            Code = "LS",
                            CapitalName = "Maseru",
                            CountryName = "Lesotho",
                            CurrencyName = "Loti"
                        },
                        new
                        {
                            Code = "LR",
                            CapitalName = "Monrovia",
                            CountryName = "Liberia",
                            CurrencyName = "Liberian Dollar"
                        },
                        new
                        {
                            Code = "LY",
                            CapitalName = "Tripoli",
                            CountryName = "Libya",
                            CurrencyName = "Libyan Dinar"
                        },
                        new
                        {
                            Code = "LI",
                            CapitalName = "Vaduz",
                            CountryName = "Liechtenstein",
                            CurrencyName = "Swiss Franc"
                        },
                        new
                        {
                            Code = "LT",
                            CapitalName = "Vilnius",
                            CountryName = "Lithuania",
                            CurrencyName = "Euro"
                        },
                        new
                        {
                            Code = "LU",
                            CapitalName = "Luxembourg City",
                            CountryName = "Luxembourg",
                            CurrencyName = "Euro"
                        },
                        new
                        {
                            Code = "MG",
                            CapitalName = "Antananarivo",
                            CountryName = "Madagascar",
                            CurrencyName = "Ariary"
                        },
                        new
                        {
                            Code = "MW",
                            CapitalName = "Lilongwe",
                            CountryName = "Malawi",
                            CurrencyName = "Malawian Kwacha"
                        },
                        new
                        {
                            Code = "MY",
                            CapitalName = "Kuala Lumpur",
                            CountryName = "Malaysia",
                            CurrencyName = "Malaysian Ringgit"
                        },
                        new
                        {
                            Code = "MV",
                            CapitalName = "Male",
                            CountryName = "Maldives",
                            CurrencyName = "Maldivian Rufiyaa"
                        },
                        new
                        {
                            Code = "ML",
                            CapitalName = "Bamako",
                            CountryName = "Mali",
                            CurrencyName = "West African CFA Franc"
                        },
                        new
                        {
                            Code = "MT",
                            CapitalName = "Valletta",
                            CountryName = "Malta",
                            CurrencyName = "Euro"
                        },
                        new
                        {
                            Code = "MH",
                            CapitalName = "Majuro",
                            CountryName = "Marshall Islands",
                            CurrencyName = "US Dollar"
                        },
                        new
                        {
                            Code = "MR",
                            CapitalName = "Nouakchott",
                            CountryName = "Mauritania",
                            CurrencyName = "Ouguiya"
                        },
                        new
                        {
                            Code = "MU",
                            CapitalName = "Port Louis",
                            CountryName = "Mauritius",
                            CurrencyName = "Mauritian Rupee"
                        },
                        new
                        {
                            Code = "MX",
                            CapitalName = "Mexico City",
                            CountryName = "Mexico",
                            CurrencyName = "Mexican Peso"
                        },
                        new
                        {
                            Code = "FM",
                            CapitalName = "Palikir",
                            CountryName = "Micronesia",
                            CurrencyName = "US Dollar"
                        },
                        new
                        {
                            Code = "MD",
                            CapitalName = "Chisinau",
                            CountryName = "Moldova",
                            CurrencyName = "Moldovan Leu"
                        },
                        new
                        {
                            Code = "MC",
                            CapitalName = "Monaco",
                            CountryName = "Monaco",
                            CurrencyName = "Euro"
                        },
                        new
                        {
                            Code = "MN",
                            CapitalName = "Ulaanbaatar",
                            CountryName = "Mongolia",
                            CurrencyName = "Tugrik"
                        },
                        new
                        {
                            Code = "ME",
                            CapitalName = "Podgorica",
                            CountryName = "Montenegro",
                            CurrencyName = "Euro"
                        },
                        new
                        {
                            Code = "MA",
                            CapitalName = "Rabat",
                            CountryName = "Morocco",
                            CurrencyName = "Moroccan Dirham"
                        },
                        new
                        {
                            Code = "MZ",
                            CapitalName = "Maputo",
                            CountryName = "Mozambique",
                            CurrencyName = "Metical"
                        },
                        new
                        {
                            Code = "MM",
                            CapitalName = "Naypyidaw",
                            CountryName = "Myanmar",
                            CurrencyName = "Kyat"
                        },
                        new
                        {
                            Code = "NA",
                            CapitalName = "Windhoek",
                            CountryName = "Namibia",
                            CurrencyName = "Namibian Dollar"
                        },
                        new
                        {
                            Code = "NR",
                            CapitalName = "Yaren",
                            CountryName = "Nauru",
                            CurrencyName = "Australian Dollar"
                        },
                        new
                        {
                            Code = "NP",
                            CapitalName = "Kathmandu",
                            CountryName = "Nepal",
                            CurrencyName = "Nepalese Rupee"
                        },
                        new
                        {
                            Code = "NL",
                            CapitalName = "Amsterdam",
                            CountryName = "Netherlands",
                            CurrencyName = "Euro"
                        },
                        new
                        {
                            Code = "NZ",
                            CapitalName = "Wellington",
                            CountryName = "New Zealand",
                            CurrencyName = "New Zealand Dollar"
                        },
                        new
                        {
                            Code = "NI",
                            CapitalName = "Managua",
                            CountryName = "Nicaragua",
                            CurrencyName = "Cordoba"
                        },
                        new
                        {
                            Code = "NE",
                            CapitalName = "Niamey",
                            CountryName = "Niger",
                            CurrencyName = "West African CFA Franc"
                        },
                        new
                        {
                            Code = "NG",
                            CapitalName = "Abuja",
                            CountryName = "Nigeria",
                            CurrencyName = "Naira"
                        },
                        new
                        {
                            Code = "MK",
                            CapitalName = "Skopje",
                            CountryName = "North Macedonia",
                            CurrencyName = "Denar"
                        },
                        new
                        {
                            Code = "NO",
                            CapitalName = "Oslo",
                            CountryName = "Norway",
                            CurrencyName = "Norwegian Krone"
                        },
                        new
                        {
                            Code = "OM",
                            CapitalName = "Muscat",
                            CountryName = "Oman",
                            CurrencyName = "Omani Rial"
                        },
                        new
                        {
                            Code = "PK",
                            CapitalName = "Islamabad",
                            CountryName = "Pakistan",
                            CurrencyName = "Pakistani Rupee"
                        },
                        new
                        {
                            Code = "PW",
                            CapitalName = "Ngerulmud",
                            CountryName = "Palau",
                            CurrencyName = "US Dollar"
                        },
                        new
                        {
                            Code = "PA",
                            CapitalName = "Panama City",
                            CountryName = "Panama",
                            CurrencyName = "Balboa"
                        },
                        new
                        {
                            Code = "PG",
                            CapitalName = "Port Moresby",
                            CountryName = "Papua New Guinea",
                            CurrencyName = "Kina"
                        },
                        new
                        {
                            Code = "PY",
                            CapitalName = "Asuncion",
                            CountryName = "Paraguay",
                            CurrencyName = "Guarani"
                        },
                        new
                        {
                            Code = "PE",
                            CapitalName = "Lima",
                            CountryName = "Peru",
                            CurrencyName = "Sol"
                        },
                        new
                        {
                            Code = "PH",
                            CapitalName = "Manila",
                            CountryName = "Philippines",
                            CurrencyName = "Philippine Peso"
                        },
                        new
                        {
                            Code = "PL",
                            CapitalName = "Warsaw",
                            CountryName = "Poland",
                            CurrencyName = "Zloty"
                        },
                        new
                        {
                            Code = "PT",
                            CapitalName = "Lisbon",
                            CountryName = "Portugal",
                            CurrencyName = "Euro"
                        },
                        new
                        {
                            Code = "QA",
                            CapitalName = "Doha",
                            CountryName = "Qatar",
                            CurrencyName = "Qatari Riyal"
                        },
                        new
                        {
                            Code = "RO",
                            CapitalName = "Bucharest",
                            CountryName = "Romania",
                            CurrencyName = "Romanian Leu"
                        },
                        new
                        {
                            Code = "RU",
                            CapitalName = "Moscow",
                            CountryName = "Russia",
                            CurrencyName = "Russian Ruble"
                        },
                        new
                        {
                            Code = "RW",
                            CapitalName = "Kigali",
                            CountryName = "Rwanda",
                            CurrencyName = "Rwandan Franc"
                        },
                        new
                        {
                            Code = "KN",
                            CapitalName = "Basseterre",
                            CountryName = "Saint Kitts and Nevis",
                            CurrencyName = "East Caribbean Dollar"
                        },
                        new
                        {
                            Code = "LC",
                            CapitalName = "Castries",
                            CountryName = "Saint Lucia",
                            CurrencyName = "East Caribbean Dollar"
                        },
                        new
                        {
                            Code = "VC",
                            CapitalName = "Kingstown",
                            CountryName = "Saint Vincent and the Grenadines",
                            CurrencyName = "East Caribbean Dollar"
                        },
                        new
                        {
                            Code = "WS",
                            CapitalName = "Apia",
                            CountryName = "Samoa",
                            CurrencyName = "Tala"
                        },
                        new
                        {
                            Code = "SM",
                            CapitalName = "San Marino",
                            CountryName = "San Marino",
                            CurrencyName = "Euro"
                        },
                        new
                        {
                            Code = "ST",
                            CapitalName = "Sao Tome",
                            CountryName = "Sao Tome and Principe",
                            CurrencyName = "Dobra"
                        },
                        new
                        {
                            Code = "SA",
                            CapitalName = "Riyadh",
                            CountryName = "Saudi Arabia",
                            CurrencyName = "Saudi Riyal"
                        },
                        new
                        {
                            Code = "SN",
                            CapitalName = "Dakar",
                            CountryName = "Senegal",
                            CurrencyName = "West African CFA Franc"
                        },
                        new
                        {
                            Code = "RS",
                            CapitalName = "Belgrade",
                            CountryName = "Serbia",
                            CurrencyName = "Serbian Dinar"
                        },
                        new
                        {
                            Code = "SC",
                            CapitalName = "Victoria",
                            CountryName = "Seychelles",
                            CurrencyName = "Seychellois Rupee"
                        },
                        new
                        {
                            Code = "SL",
                            CapitalName = "Freetown",
                            CountryName = "Sierra Leone",
                            CurrencyName = "Leone"
                        },
                        new
                        {
                            Code = "SG",
                            CapitalName = "Singapore",
                            CountryName = "Singapore",
                            CurrencyName = "Singapore Dollar"
                        },
                        new
                        {
                            Code = "SK",
                            CapitalName = "Bratislava",
                            CountryName = "Slovakia",
                            CurrencyName = "Euro"
                        },
                        new
                        {
                            Code = "SI",
                            CapitalName = "Ljubljana",
                            CountryName = "Slovenia",
                            CurrencyName = "Euro"
                        },
                        new
                        {
                            Code = "SB",
                            CapitalName = "Honiara",
                            CountryName = "Solomon Islands",
                            CurrencyName = "Solomon Islands Dollar"
                        },
                        new
                        {
                            Code = "SO",
                            CapitalName = "Mogadishu",
                            CountryName = "Somalia",
                            CurrencyName = "Somali Shilling"
                        },
                        new
                        {
                            Code = "ZA",
                            CapitalName = "Pretoria",
                            CountryName = "South Africa",
                            CurrencyName = "South African Rand"
                        },
                        new
                        {
                            Code = "SS",
                            CapitalName = "Juba",
                            CountryName = "South Sudan",
                            CurrencyName = "South Sudanese Pound"
                        },
                        new
                        {
                            Code = "ES",
                            CapitalName = "Madrid",
                            CountryName = "Spain",
                            CurrencyName = "Euro"
                        },
                        new
                        {
                            Code = "LK",
                            CapitalName = "Sri Jayawardenepura Kotte",
                            CountryName = "Sri Lanka",
                            CurrencyName = "Sri Lankan Rupee"
                        },
                        new
                        {
                            Code = "SD",
                            CapitalName = "Khartoum",
                            CountryName = "Sudan",
                            CurrencyName = "Sudanese Pound"
                        },
                        new
                        {
                            Code = "SR",
                            CapitalName = "Paramaribo",
                            CountryName = "Suriname",
                            CurrencyName = "Surinamese Dollar"
                        },
                        new
                        {
                            Code = "SE",
                            CapitalName = "Stockholm",
                            CountryName = "Sweden",
                            CurrencyName = "Swedish Krona"
                        },
                        new
                        {
                            Code = "CH",
                            CapitalName = "Bern",
                            CountryName = "Switzerland",
                            CurrencyName = "Swiss Franc"
                        },
                        new
                        {
                            Code = "SY",
                            CapitalName = "Damascus",
                            CountryName = "Syria",
                            CurrencyName = "Syrian Pound"
                        },
                        new
                        {
                            Code = "TW",
                            CapitalName = "Taipei",
                            CountryName = "Taiwan",
                            CurrencyName = "New Taiwan Dollar"
                        },
                        new
                        {
                            Code = "TJ",
                            CapitalName = "Dushanbe",
                            CountryName = "Tajikistan",
                            CurrencyName = "Somoni"
                        },
                        new
                        {
                            Code = "TZ",
                            CapitalName = "Dodoma",
                            CountryName = "Tanzania",
                            CurrencyName = "Tanzanian Shilling"
                        },
                        new
                        {
                            Code = "TH",
                            CapitalName = "Bangkok",
                            CountryName = "Thailand",
                            CurrencyName = "Baht"
                        },
                        new
                        {
                            Code = "TL",
                            CapitalName = "Dili",
                            CountryName = "Timor-Leste",
                            CurrencyName = "US Dollar"
                        },
                        new
                        {
                            Code = "TG",
                            CapitalName = "Lome",
                            CountryName = "Togo",
                            CurrencyName = "West African CFA Franc"
                        },
                        new
                        {
                            Code = "TO",
                            CapitalName = "Nuku'alofa",
                            CountryName = "Tonga",
                            CurrencyName = "Pa'anga"
                        },
                        new
                        {
                            Code = "TT",
                            CapitalName = "Port of Spain",
                            CountryName = "Trinidad and Tobago",
                            CurrencyName = "Trinidad and Tobago Dollar"
                        },
                        new
                        {
                            Code = "TN",
                            CapitalName = "Tunis",
                            CountryName = "Tunisia",
                            CurrencyName = "Tunisian Dinar"
                        },
                        new
                        {
                            Code = "TR",
                            CapitalName = "Ankara",
                            CountryName = "Turkey",
                            CurrencyName = "Turkish Lira"
                        },
                        new
                        {
                            Code = "TM",
                            CapitalName = "Ashgabat",
                            CountryName = "Turkmenistan",
                            CurrencyName = "Turkmen Manat"
                        },
                        new
                        {
                            Code = "TV",
                            CapitalName = "Funafuti",
                            CountryName = "Tuvalu",
                            CurrencyName = "Australian Dollar"
                        },
                        new
                        {
                            Code = "UG",
                            CapitalName = "Kampala",
                            CountryName = "Uganda",
                            CurrencyName = "Ugandan Shilling"
                        },
                        new
                        {
                            Code = "UA",
                            CapitalName = "Kyiv",
                            CountryName = "Ukraine",
                            CurrencyName = "Hryvnia"
                        },
                        new
                        {
                            Code = "AE",
                            CapitalName = "Abu Dhabi",
                            CountryName = "United Arab Emirates",
                            CurrencyName = "UAE Dirham"
                        },
                        new
                        {
                            Code = "GB",
                            CapitalName = "London",
                            CountryName = "United Kingdom",
                            CurrencyName = "Pound Sterling"
                        },
                        new
                        {
                            Code = "US",
                            CapitalName = "Washington, D.C.",
                            CountryName = "United States",
                            CurrencyName = "US Dollar"
                        },
                        new
                        {
                            Code = "UY",
                            CapitalName = "Montevideo",
                            CountryName = "Uruguay",
                            CurrencyName = "Uruguayan Peso"
                        },
                        new
                        {
                            Code = "UZ",
                            CapitalName = "Tashkent",
                            CountryName = "Uzbekistan",
                            CurrencyName = "Uzbekistani Som"
                        },
                        new
                        {
                            Code = "VU",
                            CapitalName = "Port Vila",
                            CountryName = "Vanuatu",
                            CurrencyName = "Vatu"
                        },
                        new
                        {
                            Code = "VA",
                            CapitalName = "Vatican City",
                            CountryName = "Vatican City",
                            CurrencyName = "Euro"
                        },
                        new
                        {
                            Code = "VE",
                            CapitalName = "Caracas",
                            CountryName = "Venezuela",
                            CurrencyName = "Bolivar"
                        },
                        new
                        {
                            Code = "VN",
                            CapitalName = "Hanoi",
                            CountryName = "Vietnam",
                            CurrencyName = "Dong"
                        },
                        new
                        {
                            Code = "YE",
                            CapitalName = "Sana'a",
                            CountryName = "Yemen",
                            CurrencyName = "Yemeni Rial"
                        },
                        new
                        {
                            Code = "ZM",
                            CapitalName = "Lusaka",
                            CountryName = "Zambia",
                            CurrencyName = "Zambian Kwacha"
                        },
                        new
                        {
                            Code = "ZW",
                            CapitalName = "Harare",
                            CountryName = "Zimbabwe",
                            CurrencyName = "Zimbabwe Gold"
                        });
                });

            modelBuilder.Entity("EmptyProjectTesting.Entites.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HOD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Department", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HOD = "Dr. Rajesh Sharma",
                            Name = "Computer Science Department"
                        },
                        new
                        {
                            Id = 2,
                            HOD = "Dr. Priya Verma",
                            Name = "Information Technology Department"
                        },
                        new
                        {
                            Id = 3,
                            HOD = "Dr. Amit Gupta",
                            Name = "Electronics Engineering Department"
                        },
                        new
                        {
                            Id = 4,
                            HOD = "Dr. Vikram Singh",
                            Name = "Mechanical Engineering Department"
                        },
                        new
                        {
                            Id = 5,
                            HOD = "Dr. Neha Bansal",
                            Name = "Civil Engineering Department"
                        },
                        new
                        {
                            Id = 6,
                            HOD = "Dr. Anil Kumar",
                            Name = "Electrical Engineering Department"
                        },
                        new
                        {
                            Id = 7,
                            HOD = "Dr. Sunita Mehta",
                            Name = "Mathematics Department"
                        },
                        new
                        {
                            Id = 8,
                            HOD = "Dr. Rakesh Malhotra",
                            Name = "Physics Department"
                        },
                        new
                        {
                            Id = 9,
                            HOD = "Dr. Pooja Arora",
                            Name = "Chemistry Department"
                        },
                        new
                        {
                            Id = 10,
                            HOD = "Dr. Rabindranath Tagore",
                            Name = "Biology Department"
                        },
                        new
                        {
                            Id = 11,
                            HOD = "Dr. Deepak Aggarwal",
                            Name = "Commerce Department"
                        },
                        new
                        {
                            Id = 12,
                            HOD = "Dr. Kavita Yadav",
                            Name = "Management Studies Department"
                        },
                        new
                        {
                            Id = 13,
                            HOD = "Dr. Nitin Sethi",
                            Name = "Economics Department"
                        },
                        new
                        {
                            Id = 14,
                            HOD = "Dr. Shalini Kapoor",
                            Name = "English Department"
                        },
                        new
                        {
                            Id = 15,
                            HOD = "Dr. Suresh Chandra",
                            Name = "Hindi Department"
                        },
                        new
                        {
                            Id = 16,
                            HOD = "Dr. Ashok Mishra",
                            Name = "History Department"
                        },
                        new
                        {
                            Id = 17,
                            HOD = "Dr. Meenakshi Jain",
                            Name = "Political Science Department"
                        },
                        new
                        {
                            Id = 18,
                            HOD = "Dr. Rohit Khanna",
                            Name = "Psychology Department"
                        },
                        new
                        {
                            Id = 19,
                            HOD = "Dr. Garima Joshi",
                            Name = "Environmental Science Department"
                        },
                        new
                        {
                            Id = 20,
                            HOD = "Dr. Arjun Malhotra",
                            Name = "Data Science Department"
                        });
                });

            modelBuilder.Entity("EmptyProjectTesting.Entites.SpiralNotebook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("SpiralNotebooks", (string)null);
                });

            modelBuilder.Entity("EmptyProjectTesting.Entites.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("EmptyProjectTesting.Entites.Student", b =>
                {
                    b.HasOne("EmptyProjectTesting.Entites.CountryFlag", "CountryFlag")
                        .WithMany("Students")
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmptyProjectTesting.Entites.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CountryFlag");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EmptyProjectTesting.Entites.CountryFlag", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("EmptyProjectTesting.Entites.Department", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
