using EmptyProjectTesting.Entites;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace EmptyProjectTesting.Entity_Configuration
{
    public class CountryFlagConfiguration : IEntityTypeConfiguration<CountryFlag>
    {
        public void Configure(EntityTypeBuilder<CountryFlag> builder)
        {
            builder.HasData(
                new CountryFlag { Code = "AF", CountryName = "Afghanistan", CapitalName = "Kabul", CurrencyName = "Afghani" },
                new CountryFlag { Code = "AL", CountryName = "Albania", CapitalName = "Tirana", CurrencyName = "Lek" },
                new CountryFlag { Code = "DZ", CountryName = "Algeria", CapitalName = "Algiers", CurrencyName = "Algerian Dinar" },
                new CountryFlag { Code = "AD", CountryName = "Andorra", CapitalName = "Andorra la Vella", CurrencyName = "Euro" },
                new CountryFlag { Code = "AO", CountryName = "Angola", CapitalName = "Luanda", CurrencyName = "Kwanza" },
                new CountryFlag { Code = "AG", CountryName = "Antigua and Barbuda", CapitalName = "Saint John's", CurrencyName = "East Caribbean Dollar" },
                new CountryFlag { Code = "AR", CountryName = "Argentina", CapitalName = "Buenos Aires", CurrencyName = "Argentine Peso" },
                new CountryFlag { Code = "AM", CountryName = "Armenia", CapitalName = "Yerevan", CurrencyName = "Armenian Dram" },
                new CountryFlag { Code = "AU", CountryName = "Australia", CapitalName = "Canberra", CurrencyName = "Australian Dollar" },
                new CountryFlag { Code = "AT", CountryName = "Austria", CapitalName = "Vienna", CurrencyName = "Euro" },

                new CountryFlag { Code = "AZ", CountryName = "Azerbaijan", CapitalName = "Baku", CurrencyName = "Azerbaijani Manat" },
                new CountryFlag { Code = "BS", CountryName = "Bahamas", CapitalName = "Nassau", CurrencyName = "Bahamian Dollar" },
                new CountryFlag { Code = "BH", CountryName = "Bahrain", CapitalName = "Manama", CurrencyName = "Bahraini Dinar" },
                new CountryFlag { Code = "BD", CountryName = "Bangladesh", CapitalName = "Dhaka", CurrencyName = "Taka" },
                new CountryFlag { Code = "BB", CountryName = "Barbados", CapitalName = "Bridgetown", CurrencyName = "Barbadian Dollar" },
                new CountryFlag { Code = "BY", CountryName = "Belarus", CapitalName = "Minsk", CurrencyName = "Belarusian Ruble" },
                new CountryFlag { Code = "BE", CountryName = "Belgium", CapitalName = "Brussels", CurrencyName = "Euro" },
                new CountryFlag { Code = "BZ", CountryName = "Belize", CapitalName = "Belmopan", CurrencyName = "Belize Dollar" },
                new CountryFlag { Code = "BJ", CountryName = "Benin", CapitalName = "Porto-Novo", CurrencyName = "West African CFA Franc" },
                new CountryFlag { Code = "BT", CountryName = "Bhutan", CapitalName = "Thimphu", CurrencyName = "Ngultrum" },

                new CountryFlag { Code = "BO", CountryName = "Bolivia", CapitalName = "Sucre", CurrencyName = "Boliviano" },
                new CountryFlag { Code = "BA", CountryName = "Bosnia and Herzegovina", CapitalName = "Sarajevo", CurrencyName = "Convertible Mark" },
                new CountryFlag { Code = "BW", CountryName = "Botswana", CapitalName = "Gaborone", CurrencyName = "Pula" },
                new CountryFlag { Code = "BR", CountryName = "Brazil", CapitalName = "Brasilia", CurrencyName = "Brazilian Real" },
                new CountryFlag { Code = "BN", CountryName = "Brunei", CapitalName = "Bandar Seri Begawan", CurrencyName = "Brunei Dollar" },
                new CountryFlag { Code = "BG", CountryName = "Bulgaria", CapitalName = "Sofia", CurrencyName = "Bulgarian Lev" },
                new CountryFlag { Code = "BF", CountryName = "Burkina Faso", CapitalName = "Ouagadougou", CurrencyName = "West African CFA Franc" },
                new CountryFlag { Code = "BI", CountryName = "Burundi", CapitalName = "Gitega", CurrencyName = "Burundian Franc" },
                new CountryFlag { Code = "CV", CountryName = "Cabo Verde", CapitalName = "Praia", CurrencyName = "Cape Verdean Escudo" },
                new CountryFlag { Code = "KH", CountryName = "Cambodia", CapitalName = "Phnom Penh", CurrencyName = "Riel" },

                new CountryFlag { Code = "CM", CountryName = "Cameroon", CapitalName = "Yaounde", CurrencyName = "Central African CFA Franc" },
                new CountryFlag { Code = "CA", CountryName = "Canada", CapitalName = "Ottawa", CurrencyName = "Canadian Dollar" },
                new CountryFlag { Code = "CF", CountryName = "Central African Republic", CapitalName = "Bangui", CurrencyName = "Central African CFA    Franc" },
                new CountryFlag { Code = "TD", CountryName = "Chad", CapitalName = "N'Djamena", CurrencyName = "Central African CFA Franc" },
                new CountryFlag { Code = "CL", CountryName = "Chile", CapitalName = "Santiago", CurrencyName = "Chilean Peso" },
                new CountryFlag { Code = "CN", CountryName = "China", CapitalName = "Beijing", CurrencyName = "Chinese Yuan" },
                new CountryFlag { Code = "CO", CountryName = "Colombia", CapitalName = "Bogota", CurrencyName = "Colombian Peso" },
                new CountryFlag { Code = "KM", CountryName = "Comoros", CapitalName = "Moroni", CurrencyName = "Comorian Franc" },
                new CountryFlag { Code = "CG", CountryName = "Republic of the Congo", CapitalName = "Brazzaville", CurrencyName = "Central African CFA  Franc" },
                new CountryFlag { Code = "CD", CountryName = "Democratic Republic of the Congo", CapitalName = "Kinshasa", CurrencyName = "Congolese    Franc" },

                new CountryFlag { Code = "CR", CountryName = "Costa Rica", CapitalName = "San Jose", CurrencyName = "Costa Rican Colon" },
                new CountryFlag { Code = "CI", CountryName = "Cote d'Ivoire", CapitalName = "Yamoussoukro", CurrencyName = "West African CFA Franc" },
                new CountryFlag { Code = "HR", CountryName = "Croatia", CapitalName = "Zagreb", CurrencyName = "Euro" },
                new CountryFlag { Code = "CU", CountryName = "Cuba", CapitalName = "Havana", CurrencyName = "Cuban Peso" },
                new CountryFlag { Code = "CY", CountryName = "Cyprus", CapitalName = "Nicosia", CurrencyName = "Euro" },
                new CountryFlag { Code = "CZ", CountryName = "Czech Republic", CapitalName = "Prague", CurrencyName = "Czech Koruna" },
                new CountryFlag { Code = "DK", CountryName = "Denmark", CapitalName = "Copenhagen", CurrencyName = "Danish Krone" },
                new CountryFlag { Code = "DJ", CountryName = "Djibouti", CapitalName = "Djibouti", CurrencyName = "Djiboutian Franc" },
                new CountryFlag { Code = "DM", CountryName = "Dominica", CapitalName = "Roseau", CurrencyName = "East Caribbean Dollar" },
                new CountryFlag { Code = "DO", CountryName = "Dominican Republic", CapitalName = "Santo Domingo", CurrencyName = "Dominican Peso" },

             

                new CountryFlag { Code = "EC", CountryName = "Ecuador", CapitalName = "Quito", CurrencyName = "US Dollar" },
                new CountryFlag { Code = "EG", CountryName = "Egypt", CapitalName = "Cairo", CurrencyName = "Egyptian Pound" },
                new CountryFlag { Code = "SV", CountryName = "El Salvador", CapitalName = "San Salvador", CurrencyName = "US Dollar" },
                new CountryFlag { Code = "GQ", CountryName = "Equatorial Guinea", CapitalName = "Malabo", CurrencyName = "Central African CFA Franc" },
                new CountryFlag { Code = "ER", CountryName = "Eritrea", CapitalName = "Asmara", CurrencyName = "Nakfa" },
                new CountryFlag { Code = "EE", CountryName = "Estonia", CapitalName = "Tallinn", CurrencyName = "Euro" },
                new CountryFlag { Code = "SZ", CountryName = "Eswatini", CapitalName = "Mbabane", CurrencyName = "Lilangeni" },
                new CountryFlag { Code = "ET", CountryName = "Ethiopia", CapitalName = "Addis Ababa", CurrencyName = "Birr" },
                new CountryFlag { Code = "FJ", CountryName = "Fiji", CapitalName = "Suva", CurrencyName = "Fijian Dollar" },
                new CountryFlag { Code = "FI", CountryName = "Finland", CapitalName = "Helsinki", CurrencyName = "Euro" },

                new CountryFlag { Code = "FR", CountryName = "France", CapitalName = "Paris", CurrencyName = "Euro" },
                new CountryFlag { Code = "GA", CountryName = "Gabon", CapitalName = "Libreville", CurrencyName = "Central African CFA Franc" },
                new CountryFlag { Code = "GM", CountryName = "Gambia", CapitalName = "Banjul", CurrencyName = "Dalasi" },
                new CountryFlag { Code = "GE", CountryName = "Georgia", CapitalName = "Tbilisi", CurrencyName = "Georgian Lari" },
                new CountryFlag { Code = "DE", CountryName = "Germany", CapitalName = "Berlin", CurrencyName = "Euro" },
                new CountryFlag { Code = "GH", CountryName = "Ghana", CapitalName = "Accra", CurrencyName = "Ghanaian Cedi" },
                new CountryFlag { Code = "GR", CountryName = "Greece", CapitalName = "Athens", CurrencyName = "Euro" },
                new CountryFlag { Code = "GD", CountryName = "Grenada", CapitalName = "St. George's", CurrencyName = "East Caribbean Dollar" },
                new CountryFlag { Code = "GT", CountryName = "Guatemala", CapitalName = "Guatemala City", CurrencyName = "Quetzal" },
                new CountryFlag { Code = "GN", CountryName = "Guinea", CapitalName = "Conakry", CurrencyName = "Guinean Franc" },

                new CountryFlag { Code = "GW", CountryName = "Guinea-Bissau", CapitalName = "Bissau", CurrencyName = "West African CFA Franc" },
                new CountryFlag { Code = "GY", CountryName = "Guyana", CapitalName = "Georgetown", CurrencyName = "Guyanese Dollar" },
                new CountryFlag { Code = "HT", CountryName = "Haiti", CapitalName = "Port-au-Prince", CurrencyName = "Gourde" },
                new CountryFlag { Code = "HN", CountryName = "Honduras", CapitalName = "Tegucigalpa", CurrencyName = "Lempira" },
                new CountryFlag { Code = "HU", CountryName = "Hungary", CapitalName = "Budapest", CurrencyName = "Forint" },
                new CountryFlag { Code = "IS", CountryName = "Iceland", CapitalName = "Reykjavik", CurrencyName = "Icelandic Krona" },
                new CountryFlag { Code = "IN", CountryName = "India", CapitalName = "New Delhi", CurrencyName = "Indian Rupee" },
                new CountryFlag { Code = "ID", CountryName = "Indonesia", CapitalName = "Jakarta", CurrencyName = "Rupiah" },
                new CountryFlag { Code = "IR", CountryName = "Iran", CapitalName = "Tehran", CurrencyName = "Iranian Rial" },
                new CountryFlag { Code = "IQ", CountryName = "Iraq", CapitalName = "Baghdad", CurrencyName = "Iraqi Dinar" },

                new CountryFlag { Code = "IE", CountryName = "Ireland", CapitalName = "Dublin", CurrencyName = "Euro" },
                new CountryFlag { Code = "IL", CountryName = "Israel", CapitalName = "Jerusalem", CurrencyName = "Israeli New Shekel" },
                new CountryFlag { Code = "IT", CountryName = "Italy", CapitalName = "Rome", CurrencyName = "Euro" },
                new CountryFlag { Code = "JM", CountryName = "Jamaica", CapitalName = "Kingston", CurrencyName = "Jamaican Dollar" },
                new CountryFlag { Code = "JP", CountryName = "Japan", CapitalName = "Tokyo", CurrencyName = "Japanese Yen" },
                new CountryFlag { Code = "JO", CountryName = "Jordan", CapitalName = "Amman", CurrencyName = "Jordanian Dinar" },
                new CountryFlag { Code = "KZ", CountryName = "Kazakhstan", CapitalName = "Astana", CurrencyName = "Tenge" },
                new CountryFlag { Code = "KE", CountryName = "Kenya", CapitalName = "Nairobi", CurrencyName = "Kenyan Shilling" },
                new CountryFlag { Code = "KI", CountryName = "Kiribati", CapitalName = "South Tarawa", CurrencyName = "Australian Dollar" },
                new CountryFlag { Code = "KP", CountryName = "North Korea", CapitalName = "Pyongyang", CurrencyName = "North Korean Won" },

                new CountryFlag { Code = "KR", CountryName = "South Korea", CapitalName = "Seoul", CurrencyName = "South Korean Won" },
                new CountryFlag { Code = "KW", CountryName = "Kuwait", CapitalName = "Kuwait City", CurrencyName = "Kuwaiti Dinar" },
                new CountryFlag { Code = "KG", CountryName = "Kyrgyzstan", CapitalName = "Bishkek", CurrencyName = "Som" },
                new CountryFlag { Code = "LA", CountryName = "Laos", CapitalName = "Vientiane", CurrencyName = "Kip" },
                new CountryFlag { Code = "LV", CountryName = "Latvia", CapitalName = "Riga", CurrencyName = "Euro" },
                new CountryFlag { Code = "LB", CountryName = "Lebanon", CapitalName = "Beirut", CurrencyName = "Lebanese Pound" },
                new CountryFlag { Code = "LS", CountryName = "Lesotho", CapitalName = "Maseru", CurrencyName = "Loti" },
                new CountryFlag { Code = "LR", CountryName = "Liberia", CapitalName = "Monrovia", CurrencyName = "Liberian Dollar" },
                new CountryFlag { Code = "LY", CountryName = "Libya", CapitalName = "Tripoli", CurrencyName = "Libyan Dinar" },
                new CountryFlag { Code = "LI", CountryName = "Liechtenstein", CapitalName = "Vaduz", CurrencyName = "Swiss Franc" },



                new CountryFlag { Code = "LT", CountryName = "Lithuania", CapitalName = "Vilnius", CurrencyName = "Euro" },
                new CountryFlag { Code = "LU", CountryName = "Luxembourg", CapitalName = "Luxembourg City", CurrencyName = "Euro" },
                new CountryFlag { Code = "MG", CountryName = "Madagascar", CapitalName = "Antananarivo", CurrencyName = "Ariary" },
                new CountryFlag { Code = "MW", CountryName = "Malawi", CapitalName = "Lilongwe", CurrencyName = "Malawian Kwacha" },
                new CountryFlag { Code = "MY", CountryName = "Malaysia", CapitalName = "Kuala Lumpur", CurrencyName = "Malaysian Ringgit" },
                new CountryFlag { Code = "MV", CountryName = "Maldives", CapitalName = "Male", CurrencyName = "Maldivian Rufiyaa" },
                new CountryFlag { Code = "ML", CountryName = "Mali", CapitalName = "Bamako", CurrencyName = "West African CFA Franc" },
                new CountryFlag { Code = "MT", CountryName = "Malta", CapitalName = "Valletta", CurrencyName = "Euro" },
                new CountryFlag { Code = "MH", CountryName = "Marshall Islands", CapitalName = "Majuro", CurrencyName = "US Dollar" },
                new CountryFlag { Code = "MR", CountryName = "Mauritania", CapitalName = "Nouakchott", CurrencyName = "Ouguiya" },

                new CountryFlag { Code = "MU", CountryName = "Mauritius", CapitalName = "Port Louis", CurrencyName = "Mauritian Rupee" },
                new CountryFlag { Code = "MX", CountryName = "Mexico", CapitalName = "Mexico City", CurrencyName = "Mexican Peso" },
                new CountryFlag { Code = "FM", CountryName = "Micronesia", CapitalName = "Palikir", CurrencyName = "US Dollar" },
                new CountryFlag { Code = "MD", CountryName = "Moldova", CapitalName = "Chisinau", CurrencyName = "Moldovan Leu" },
                new CountryFlag { Code = "MC", CountryName = "Monaco", CapitalName = "Monaco", CurrencyName = "Euro" },
                new CountryFlag { Code = "MN", CountryName = "Mongolia", CapitalName = "Ulaanbaatar", CurrencyName = "Tugrik" },
                new CountryFlag { Code = "ME", CountryName = "Montenegro", CapitalName = "Podgorica", CurrencyName = "Euro" },
                new CountryFlag { Code = "MA", CountryName = "Morocco", CapitalName = "Rabat", CurrencyName = "Moroccan Dirham" },
                new CountryFlag { Code = "MZ", CountryName = "Mozambique", CapitalName = "Maputo", CurrencyName = "Metical" },
                new CountryFlag { Code = "MM", CountryName = "Myanmar", CapitalName = "Naypyidaw", CurrencyName = "Kyat" },

                new CountryFlag { Code = "NA", CountryName = "Namibia", CapitalName = "Windhoek", CurrencyName = "Namibian Dollar" },
                new CountryFlag { Code = "NR", CountryName = "Nauru", CapitalName = "Yaren", CurrencyName = "Australian Dollar" },
                new CountryFlag { Code = "NP", CountryName = "Nepal", CapitalName = "Kathmandu", CurrencyName = "Nepalese Rupee" },
                new CountryFlag { Code = "NL", CountryName = "Netherlands", CapitalName = "Amsterdam", CurrencyName = "Euro" },
                new CountryFlag { Code = "NZ", CountryName = "New Zealand", CapitalName = "Wellington", CurrencyName = "New Zealand Dollar" },
                new CountryFlag { Code = "NI", CountryName = "Nicaragua", CapitalName = "Managua", CurrencyName = "Cordoba" },
                new CountryFlag { Code = "NE", CountryName = "Niger", CapitalName = "Niamey", CurrencyName = "West African CFA Franc" },
                new CountryFlag { Code = "NG", CountryName = "Nigeria", CapitalName = "Abuja", CurrencyName = "Naira" },
                new CountryFlag { Code = "MK", CountryName = "North Macedonia", CapitalName = "Skopje", CurrencyName = "Denar" },
                new CountryFlag { Code = "NO", CountryName = "Norway", CapitalName = "Oslo", CurrencyName = "Norwegian Krone" },

                new CountryFlag { Code = "OM", CountryName = "Oman", CapitalName = "Muscat", CurrencyName = "Omani Rial" },
                new CountryFlag { Code = "PK", CountryName = "Pakistan", CapitalName = "Islamabad", CurrencyName = "Pakistani Rupee" },
                new CountryFlag { Code = "PW", CountryName = "Palau", CapitalName = "Ngerulmud", CurrencyName = "US Dollar" },
                new CountryFlag { Code = "PA", CountryName = "Panama", CapitalName = "Panama City", CurrencyName = "Balboa" },
                new CountryFlag { Code = "PG", CountryName = "Papua New Guinea", CapitalName = "Port Moresby", CurrencyName = "Kina" },
                new CountryFlag { Code = "PY", CountryName = "Paraguay", CapitalName = "Asuncion", CurrencyName = "Guarani" },
                new CountryFlag { Code = "PE", CountryName = "Peru", CapitalName = "Lima", CurrencyName = "Sol" },
                new CountryFlag { Code = "PH", CountryName = "Philippines", CapitalName = "Manila", CurrencyName = "Philippine Peso" },
                new CountryFlag { Code = "PL", CountryName = "Poland", CapitalName = "Warsaw", CurrencyName = "Zloty" },
                new CountryFlag { Code = "PT", CountryName = "Portugal", CapitalName = "Lisbon", CurrencyName = "Euro" },

                new CountryFlag { Code = "QA", CountryName = "Qatar", CapitalName = "Doha", CurrencyName = "Qatari Riyal" },
                new CountryFlag { Code = "RO", CountryName = "Romania", CapitalName = "Bucharest", CurrencyName = "Romanian Leu" },
                new CountryFlag { Code = "RU", CountryName = "Russia", CapitalName = "Moscow", CurrencyName = "Russian Ruble" },
                new CountryFlag { Code = "RW", CountryName = "Rwanda", CapitalName = "Kigali", CurrencyName = "Rwandan Franc" },
                new CountryFlag { Code = "KN", CountryName = "Saint Kitts and Nevis", CapitalName = "Basseterre", CurrencyName = "East Caribbean Dollar" },
                new CountryFlag { Code = "LC", CountryName = "Saint Lucia", CapitalName = "Castries", CurrencyName = "East Caribbean Dollar" },
                new CountryFlag { Code = "VC", CountryName = "Saint Vincent and the Grenadines", CapitalName = "Kingstown", CurrencyName = "East Caribbean Dollar" },
                new CountryFlag { Code = "WS", CountryName = "Samoa", CapitalName = "Apia", CurrencyName = "Tala" },
                new CountryFlag { Code = "SM", CountryName = "San Marino", CapitalName = "San Marino", CurrencyName = "Euro" },
                new CountryFlag { Code = "ST", CountryName = "Sao Tome and Principe", CapitalName = "Sao Tome", CurrencyName = "Dobra" },


                new CountryFlag { Code = "SA", CountryName = "Saudi Arabia", CapitalName = "Riyadh", CurrencyName = "Saudi Riyal" },
                new CountryFlag { Code = "SN", CountryName = "Senegal", CapitalName = "Dakar", CurrencyName = "West African CFA Franc" },
                new CountryFlag { Code = "RS", CountryName = "Serbia", CapitalName = "Belgrade", CurrencyName = "Serbian Dinar" },
                new CountryFlag { Code = "SC", CountryName = "Seychelles", CapitalName = "Victoria", CurrencyName = "Seychellois Rupee" },
                new CountryFlag { Code = "SL", CountryName = "Sierra Leone", CapitalName = "Freetown", CurrencyName = "Leone" },
                new CountryFlag { Code = "SG", CountryName = "Singapore", CapitalName = "Singapore", CurrencyName = "Singapore Dollar" },
                new CountryFlag { Code = "SK", CountryName = "Slovakia", CapitalName = "Bratislava", CurrencyName = "Euro" },
                new CountryFlag { Code = "SI", CountryName = "Slovenia", CapitalName = "Ljubljana", CurrencyName = "Euro" },
                new CountryFlag { Code = "SB", CountryName = "Solomon Islands", CapitalName = "Honiara", CurrencyName = "Solomon Islands Dollar" },
                new CountryFlag { Code = "SO", CountryName = "Somalia", CapitalName = "Mogadishu", CurrencyName = "Somali Shilling" },

                new CountryFlag { Code = "ZA", CountryName = "South Africa", CapitalName = "Pretoria", CurrencyName = "South African Rand" },
                new CountryFlag { Code = "SS", CountryName = "South Sudan", CapitalName = "Juba", CurrencyName = "South Sudanese Pound" },
                new CountryFlag { Code = "ES", CountryName = "Spain", CapitalName = "Madrid", CurrencyName = "Euro" },
                new CountryFlag { Code = "LK", CountryName = "Sri Lanka", CapitalName = "Sri Jayawardenepura Kotte", CurrencyName = "Sri Lankan Rupee" },
                new CountryFlag { Code = "SD", CountryName = "Sudan", CapitalName = "Khartoum", CurrencyName = "Sudanese Pound" },
                new CountryFlag { Code = "SR", CountryName = "Suriname", CapitalName = "Paramaribo", CurrencyName = "Surinamese Dollar" },
                new CountryFlag { Code = "SE", CountryName = "Sweden", CapitalName = "Stockholm", CurrencyName = "Swedish Krona" },
                new CountryFlag { Code = "CH", CountryName = "Switzerland", CapitalName = "Bern", CurrencyName = "Swiss Franc" },
                new CountryFlag { Code = "SY", CountryName = "Syria", CapitalName = "Damascus", CurrencyName = "Syrian Pound" },
                new CountryFlag { Code = "TW", CountryName = "Taiwan", CapitalName = "Taipei", CurrencyName = "New Taiwan Dollar" },

                new CountryFlag { Code = "TJ", CountryName = "Tajikistan", CapitalName = "Dushanbe", CurrencyName = "Somoni" },
                new CountryFlag { Code = "TZ", CountryName = "Tanzania", CapitalName = "Dodoma", CurrencyName = "Tanzanian Shilling" },
                new CountryFlag { Code = "TH", CountryName = "Thailand", CapitalName = "Bangkok", CurrencyName = "Baht" },
                new CountryFlag { Code = "TL", CountryName = "Timor-Leste", CapitalName = "Dili", CurrencyName = "US Dollar" },
                new CountryFlag { Code = "TG", CountryName = "Togo", CapitalName = "Lome", CurrencyName = "West African CFA Franc" },
                new CountryFlag { Code = "TO", CountryName = "Tonga", CapitalName = "Nuku'alofa", CurrencyName = "Pa'anga" },
                new CountryFlag { Code = "TT", CountryName = "Trinidad and Tobago", CapitalName = "Port of Spain", CurrencyName = "Trinidad and Tobago Dollar" },
                new CountryFlag { Code = "TN", CountryName = "Tunisia", CapitalName = "Tunis", CurrencyName = "Tunisian Dinar" },
                new CountryFlag { Code = "TR", CountryName = "Turkey", CapitalName = "Ankara", CurrencyName = "Turkish Lira" },
                new CountryFlag { Code = "TM", CountryName = "Turkmenistan", CapitalName = "Ashgabat", CurrencyName = "Turkmen Manat" },

                new CountryFlag { Code = "TV", CountryName = "Tuvalu", CapitalName = "Funafuti", CurrencyName = "Australian Dollar" },
                new CountryFlag { Code = "UG", CountryName = "Uganda", CapitalName = "Kampala", CurrencyName = "Ugandan Shilling" },
                new CountryFlag { Code = "UA", CountryName = "Ukraine", CapitalName = "Kyiv", CurrencyName = "Hryvnia" },
                new CountryFlag { Code = "AE", CountryName = "United Arab Emirates", CapitalName = "Abu Dhabi", CurrencyName = "UAE Dirham" },
                new CountryFlag { Code = "GB", CountryName = "United Kingdom", CapitalName = "London", CurrencyName = "Pound Sterling" },
                new CountryFlag { Code = "US", CountryName = "United States", CapitalName = "Washington, D.C.", CurrencyName = "US Dollar" },
                new CountryFlag { Code = "UY", CountryName = "Uruguay", CapitalName = "Montevideo", CurrencyName = "Uruguayan Peso" },
                new CountryFlag { Code = "UZ", CountryName = "Uzbekistan", CapitalName = "Tashkent", CurrencyName = "Uzbekistani Som" },
                new CountryFlag { Code = "VU", CountryName = "Vanuatu", CapitalName = "Port Vila", CurrencyName = "Vatu" },
                new CountryFlag { Code = "VA", CountryName = "Vatican City", CapitalName = "Vatican City", CurrencyName = "Euro" },

                new CountryFlag { Code = "VE", CountryName = "Venezuela", CapitalName = "Caracas", CurrencyName = "Bolivar" },
                new CountryFlag { Code = "VN", CountryName = "Vietnam", CapitalName = "Hanoi", CurrencyName = "Dong" },
                new CountryFlag { Code = "YE", CountryName = "Yemen", CapitalName = "Sana'a", CurrencyName = "Yemeni Rial" },
                new CountryFlag { Code = "ZM", CountryName = "Zambia", CapitalName = "Lusaka", CurrencyName = "Zambian Kwacha" },
                new CountryFlag { Code = "ZW", CountryName = "Zimbabwe", CapitalName = "Harare", CurrencyName = "Zimbabwe Gold" }


              );
        }
    }
}
