// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplicationBackend.Context;

#nullable disable

namespace WebApplicationBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260520040638_insertMasterData")]
    partial class insertMasterData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplicationBackend.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("WebApplicationBackend.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 54,
                            Email = "rahul@inc.com",
                            Gender = "Male",
                            JoinDate = new DateTime(2004, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberName = "Rahul Gandhi",
                            Phone = "9876543210"
                        },
                        new
                        {
                            Id = 2,
                            Age = 82,
                            Email = "kharge@inc.com",
                            Gender = "Male",
                            JoinDate = new DateTime(1969, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberName = "Mallikarjun Kharge",
                            Phone = "9876543211"
                        },
                        new
                        {
                            Id = 3,
                            Age = 53,
                            Email = "priyanka@inc.com",
                            Gender = "Female",
                            JoinDate = new DateTime(1999, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberName = "Priyanka Gandhi",
                            Phone = "9876543212"
                        },
                        new
                        {
                            Id = 4,
                            Age = 70,
                            Email = "tharoor@inc.com",
                            Gender = "Male",
                            JoinDate = new DateTime(2009, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberName = "Shashi Tharoor",
                            Phone = "9876543213"
                        },
                        new
                        {
                            Id = 5,
                            Age = 48,
                            Email = "pilot@inc.com",
                            Gender = "Male",
                            JoinDate = new DateTime(2004, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberName = "Sachin Pilot",
                            Phone = "9876543214"
                        });
                });

            modelBuilder.Entity("WebApplicationBackend.Entities.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("States");
                });

            modelBuilder.Entity("WebApplicationBackend.Entities.State", b =>
                {
                    b.HasOne("WebApplicationBackend.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });
#pragma warning restore 612, 618
        }
    }
}
